#!/usr/bin/python3

from argparse import ArgumentParser, Namespace
import subprocess

"""
Highly recommend reading the wiki:
- https://github.com/mviereck/x11docker/wiki
"""

OPTS = [
    ["-x", "--x11", "add X11 from host"],
    ["-w", "--wayland", "add Wayland from host"],
    ["-g", "--gpu", "enable GPU"],
    ["-a", "--audio", "enable audio via Pipewire"],
]


def get_args() -> Namespace:
    parser = ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    create_parser = subparsers.add_parser("create", help="create a container")

    for opt, full_opt, desc in OPTS:
        create_parser.add_argument(opt, full_opt, help=desc, action="store_true")

    create_parser.add_argument("-p", "--ports", help="publish ports to localhost")
    create_parser.add_argument("-v", "--volume", help="mount volume", nargs="?")
    create_parser.add_argument("-i", "--image", help="specify image", nargs="?")
    create_parser.add_argument("name", help="container name")

    enter_parser = subparsers.add_parser("enter", help="enter a container")
    enter_parser.add_argument("name", help="container name")

    return parser.parse_args()


def process_create(args: Namespace) -> str:
    assert args.command == "create"

    command = ["podman", "run", "-itd", "--stop-timeout=1", "--name", args.name]

    if args.x11 or args.wayland or args.gpu or args.audio:
        command.extend(["--security-opt", "label=type:container_runtime_t"])

    if args.x11 or args.wayland:
        command.extend(["--userns", "keep-id:uid=1000,gid=1000"])

    if args.x11:
        settings = """
            -v /tmp/.X11-unix:/tmp/.X11-unix:ro
            -e DISPLAY
        """
        command.extend(settings.split())

    if args.wayland or args.audio:
        command.extend(["-e", "XDG_RUNTIME_DIR=/tmp"])

    if args.wayland:
        settings = """
            -e WAYLAND_DISPLAY
            -v "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}:ro"
        """
        command.extend(settings.split())

    if args.gpu:
        settings = """
            --group-add video
            --group-add render
            --device /dev/dri
        """
        command.extend(settings.split())

    if args.audio:
        settings = """
            -v ${XDG_RUNTIME_DIR}/pipewire-0:/tmp/pipewire-0:ro
        """
        command.extend(settings.split())

    if args.volume is not None:
        volume_name = args.volume or args.name
        command.extend(["-v", f"{volume_name}:/home/user/data"])

    if args.ports:
        try:
            ports = list(map(int, args.ports.split(",")))
        except:
            print("dan: error: ports should be comma seperated integers")
            exit(1)

        for port in ports:
            command.extend(["-p", f"localhost:{port}:{port}"])

    image_name = args.image or "base"
    command.extend([image_name, "bash"])
    return " ".join(command)


def process_enter(args: Namespace) -> str:
    assert args.command == "enter"

    return f"podman exec -it {args.name} bash"


def process_args(args: Namespace) -> str:
    match args.command:
        case "create":
            return process_create(args)
        case "enter":
            return process_enter(args)

    # This should be unreachable
    print(args)
    exit(1)


if __name__ == "__main__":
    args = get_args()
    command = process_args(args)

    print()
    print(command)
    print()

    if args.command == "create":
        if input("Continue? [y/N]").lower() != "y":
            print("Aborted.")
            exit()

    # Probably insecure but allows using environment vars
    subprocess.run(command, shell=True)
