#!/bin/bash

_comp_cmd_dan()
{
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ ${COMP_CWORD} == 1 ]] ; then
        COMPREPLY=( $(compgen -W "create enter" -- "${cur}") )
        return
    fi

    # Enter
    if [[ ${COMP_WORDS[1]} == "enter" ]] ; then
        local containers
        containers=$(podman ps -a --format "{{.Names}}" --filter "status=running" 2>/dev/null)
        COMPREPLY=( $(compgen -W "${containers}" -- "${cur}") )
        return
    fi

    # Create
    if [[ ${COMP_WORDS[1]} == "create" ]] ; then
        if [[ ${cur} == -* ]] ; then
            local opts
            opts="--x11 --wayland --gpu --audio --ports --volume --image"
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return
        fi

        if [[ ${prev} == "--image" || ${prev} == "-i" ]] ; then
            local images
            images=$(podman images --format "{{index .Names 0}}" 2>/dev/null)
            COMPREPLY=( $(compgen -W "${images}" -- "${cur}") )
            return
        fi

        if [[ ${prev} == "--volume" || ${prev} == "-v" ]] ; then
            local volumes
            volumes=$(podman volume ls --format "{{.Name}}" 2>/dev/null)
            COMPREPLY=( $(compgen -W "${volumes}" -- "${cur}") )
            return
        fi
    fi
}

complete -F _comp_cmd_dan dan

# ex: filetype=sh
